### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by drukq5** [josiasMO/homebrew-jack2#1]
Apologies for being a github and homebrew noob. I'm getting this error when trying to install jack2. Any help appreciated.

```
==> ./waf install
Last 15 lines from /Users/master/Library/Logs/Homebrew/jack2/03.waf:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 1] Operation not permitted: '/usr/local/lib/libjack.0.1.0.dylib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/jack2-20200811-62419-exd4zt/jack2-1.9.14/waflib/Task.py", line 344, in process
    ret = self.run()
  File "/private/tmp/jack2-20200811-62419-exd4zt/jack2-1.9.14/waflib/Build.py", line 1122, in run
    fun(x.abspath(), y.abspath(), x.path_from(launch_node))
  File "/private/tmp/jack2-20200811-62419-exd4zt/jack2-1.9.14/waflib/Build.py", line 1189, in do_install
    raise Errors.WafError('Could not install the file %r' % tgt, e)
waflib.Errors.WafError: Could not install the file '/usr/local/lib/libjack.0.1.0.dylib'
```

**Comment by josiasMO** [comment]
Hello @drukq5 

I never finished this brew formula. It only worked if disabled root verification and ran it with sudo, which is not recommended. 

But you can execute the following commands in Terminal, which will install the package for you:

```
wget https://github.com/jackaudio/jack2/releases/download/v1.9.14/v1.9.14.tar.gz
tar -xvf v1.9.14.tar.gz 
cd jack2-1.9.14
./waf configure
./waf
sudo ./waf install
```

Hopefully this solves your issue.

**Comment by drukq5** [comment]
Awesome, thanks for your help. Tools like JackTrip and SoundJack have taken off as of late, though I think the binaries in the wild are based on Jack1.
